version: '3.8'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      blog_db:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_HOST: blog_db
      DB_USER: postgres
      DB_PASSWORD: aruzhann
      DB_DBNAME: blog_post
      DB_PORT: 5432
      JWT_KEY: my_jwt_secret

  notification:
    build: ./notification-service
    ports:
      - "8081:8081"
    depends_on:
      notify_db:
        condition: service_healthy
    environment:
      DB_HOST: notify_db
      DB_USER: postgres
      DB_PASSWORD: aruzhann
      DB_DBNAME: notifications
      DB_PORT: 5432
      JWT_KEY: my_jwt_secret

  blog_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aruzhann
      POSTGRES_DB: blog_post
    ports:
      - "5432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  notify_db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aruzhann
      POSTGRES_DB: notifications
    ports:
      - "5433:5432"
    volumes:
      - notify_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  blog_data:
  notify_data: